name: Test Application
on:
  workflow_dispatch:
  pull_request:
    types: [synchronize, opened, closed]
    branches:
      - dev
      - test

env:
  ARTIFACT_NAME: my-artifact

jobs:
  test_build:
    if: '!github.event.pull_request.merged'
    runs-on: ubuntu-latest
    steps:
      - name: Get run number
        run: |
          echo "Run number: ${{ github.event.pull_request.number }}"

      - name: Create an artifact file
        run: |
          echo hello >> file.txt

      - name: upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./file.txt
          retention-days: 14

  release_build:
    runs-on: 'ubuntu-latest'
    if: github.event.pull_request.merged
    steps:
      - name: Get run number
        run: |
          echo "Run number (release): ${{ github.event.pull_request.number }}"

      # Download artifact
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          workflow: build.yml
          name: ${{ env.ARTIFACT_NAME }}
          name_is_regexp: true
          run_number: ${{ github.event.pull_request.number }}
          workflow_conclusion: completed
          path: artifact

      - name: Extract texts from artifact
        run: |
          mapfile -t values < ./artifact/file.txt
          for val in "${values[@]}"; do
            combined_vals="$val,$combined_vals"
            echo "$val"
          done
